include: package:pedantic/analysis_options.yaml
#include: package:effective_dart/analysis_options.yaml

analyzer:
  errors:
   missing_required_param: error
   must_be_immutable: error
   unused_import: error
   prefer_final_fields: error
   empty_constructor_bodies: error
# analyzer:
#   strong-mode:
#     implicit-casts: true
#     implicit-dynamic: true
# linter:
#    rules:
#      - empty_constructor_bodies
